# -*- coding: utf-8 -*-
"""
Created on Tue Sep 15 19:03:13 2020

@author: Ehlion
"""

from wordgenerator.weightmap import weightmap as weightmap
#from wordgenerator.intervalmap import intervalmap as intervalmap

antagonist = weightmap()
antagonist.put(3,"An evil wizard")
antagonist.put(3,"A dragon")
antagonist.put(3,"The drow")
antagonist.put(3,"Goblins")
antagonist.put(3,"Kobolds")
antagonist.put(3,"A mind flayer")
antagonist.put(3,"Kobolds")
antagonist.put(3,"Evil cultists")
antagonist.put(3,"Orcs")
antagonist.put(3,"Trolls")
antagonist.put(3,"A banshee")
antagonist.put(3,"A demon lord")
antagonist.put(3,"An archdevil")
antagonist.put(3,"Giants")
antagonist.put(3,"Vampires")
antagonist.put(3,"Gnolls")
antagonist.put(3,"A werewolf")
antagonist.put(3,"A djinni")
antagonist.put(3,"A mimic")
antagonist.put(3,"A tarrasque")
antagonist.put(3,"A beholder")
antagonist.put(3,"A hag coven")
antagonist.put(3,"A lich")
antagonist.put(3,"Barbarians")
antagonist.put(3,"An aboleth")
antagonist.put(3,"A sucuubus")
antagonist.put(3,"A criminal organisation")
antagonist.put(3,"A gelatinous cube")
antagonist.put(3,"A necromancer")
antagonist.put(3,"Corrupt nobles")
antagonist.put(3,"A death knight")
antagonist.put(3,"The BBEG")
antagonist.put(3,"The bard")
antagonist.put(3,"Natural selection")
antagonist.put(1,"The DM")

action = weightmap()
action.put( 9,"killed")
action.put(10,"murdered")
action.put(10,"slautered")
action.put(10,"massacred")
action.put(10,"assassinated")
action.put( 3,"brainwashed")
action.put( 3,"captured")
action.put( 3,"banished")
action.put( 3,"enslaved")
action.put( 3,"betrayed")
action.put( 3,"sacrificed")
action.put( 3,"mauled")
action.put( 3,"stole")
action.put( 3,"blackmailed")
action.put( 3,"conned")
action.put( 3,"framed")
action.put( 3,"humiliated")
action.put( 3,"pillaged")
action.put( 3,"ate")
action.put( 3,"cursed")
action.put( 2,"befriended")
action.put( 1,"seduced")
           
victim = weightmap()
victim.put( 4,"my family")
victim.put( 4,"my hometown")
victim.put( 4,"my parents")
victim.put( 4,"my clan")
victim.put( 4,"my siblings")
victim.put( 4,"my mentors")
victim.put( 4,"my significant other")
victim.put( 4,"my master")
victim.put( 4,"my side squeeze")
victim.put( 4,"my apprentice")
victim.put( 4,"my friends")
victim.put( 4,"my previous adventuring party")
victim.put( 4,"my everyone I knew")
victim.put( 4,"my crew of sailors")
victim.put( 4,"my crew of pirates")
victim.put( 4,"my crew of noble outlaws")
victim.put( 4,"my crew of thieves")
victim.put( 4,"the tavern I basically lived in")
victim.put( 4,"my start-up business")
victim.put( 4,"my military unit")
victim.put( 4,"my social status")
victim.put( 4,"my treasure")
victim.put( 4,"my aspirations")
victim.put( 4,"my confidence")
victim.put( 3,"my honor")
victim.put( 1,"my imaginary friends")

outcome = weightmap()
outcome.put(29,"And it will have no effect on how I roleplay my character")
outcome.put(10,"And now I'm a murder hobo")
outcome.put(10,"And now I'm a lawful good stick in the mud")
outcome.put(10,"And now I seek vengeance")
outcome.put( 4,"And now I trust no one")
outcome.put( 4,"And now I have a bleak outlook of the world")
outcome.put( 4,"And now I strive to live by their ideals")
outcome.put( 4,"And now I must become stronger")
outcome.put( 5,"And now I seek to bring back what I have lost")
outcome.put( 4,"And now I vow to prevent that from happening to anyone else")
outcome.put( 4,"And now I am haunted by their memory")
outcome.put( 4,"And now I seek to uncover the truth about what happened")
outcome.put( 4,"And now I fear it will happen again")
outcome.put( 3,"And now I am stronger because of it")
outcome.put( 3,"And now I'm an alcoholic")
outcome.put( 3,"And now I have multiclassed into warlock")
outcome.put( 1,"And now I'm Batman")

print("{} {} {} {}".format(
    antagonist.draw(),
    action.draw(),
    victim.draw(),
    outcome.draw()))